//
// Created by trast on 17/09/2024.
//

#ifndef RAYTRACING_DEVELOPING_A_3D_RENDERER_FROM_ZERO_PLYCPP_RUNNER_H
#define RAYTRACING_DEVELOPING_A_3D_RENDERER_FROM_ZERO_PLYCPP_RUNNER_H

#include "plycpp.h"

#endif //RAYTRACING_DEVELOPING_A_3D_RENDERER_FROM_ZERO_PLYCPP_RUNNER_H
